services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=louay
      - POSTGRES_PASSWORD=louay
      - POSTGRES_DB=nextauth_db
    ports:
      - "5433:5432"
    volumes:
      - nextauth_data:/var/lib/postgresql/data

volumes:
  nextauth_data:
